// src/data.js

export const dataRames = {
  "MP 05": {
    nomComplet: "Matériel Pneu 2005",
    image: "mp05.png",
    constructeur: "Alstom",
    miseEnService: "2008",
    vitesseMax: "70 km/h",
    composition: "6 voitures (automatiques)",
    capacite: "~550 voyageurs",
    descriptionLongue: "Le MP 05 est un matériel sur pneus entièrement automatique (CA) commandé pour équiper la ligne 1 lors de son automatisation. Il est techniquement très proche du MP 89 CA de la ligne 14."
  },
  "MP 05 IDFM": {
    nomComplet: "Matériel Pneu 2005 (IDFM)",
    image: "mp05idfm.png",
    constructeur: "Alstom",
    miseEnService: "2008 (Rénové IDFM ~2020)",
    vitesseMax: "70 km/h",
    composition: "6 voitures (automatiques)",
    capacite: "~550 voyageurs",
    descriptionLongue: "Ces rames MP 05, libérées de la ligne 1, ont été rénovées avec la livrée Île-de-France Mobilités et transférées sur la ligne 4 pour son automatisation."
  },
  "MF 01": {
    nomComplet: "Matériel Fer 2001 (MF 2000)",
    image: "mf01.png",
    constructeur: "Alstom, Bombardier, Technic-Ateliers",
    miseEnService: "2007",
    vitesseMax: "70 km/h",
    composition: "5 voitures (boa)",
    capacite: "~540 voyageurs",
    descriptionLongue: "Le MF 01 (ou MF 2000) est le matériel fer moderne qui remplace les MF 67 sur plusieurs lignes. Il est équipé de la climatisation et de l'intercirculation 'boa' entre les voitures."
  },
  "MF 67": {
    nomComplet: "Matériel Fer 1967",
    image: "mf67.png",
    constructeur: "Brissonneau et Lotz, CIMT",
    miseEnService: "1967",
    vitesseMax: "70 km/h",
    composition: "5 voitures (ou 3 sur 3bis)",
    capacite: "~515 voyageurs (5v)",
    descriptionLongue: "Série la plus nombreuse du métro parisien, le MF 67 a équipé la majorité des lignes sur fer. Malgré son âge, il reste fiable et a connu de nombreuses rénovations."
  },
  "MP 89 CA": {
    nomComplet: "Matériel Pneu 1989 (Conduite Automatique)",
    image: "mp89ca.png",
    constructeur: "GEC Alsthom",
    miseEnService: "1997",
    vitesseMax: "80 km/h",
    composition: "6 voitures (automatiques)",
    capacite: "~720 voyageurs",
    descriptionLongue: "Premier matériel automatique du métro parisien, conçu pour la ligne 14 (Météor). Ces rames à 6 voitures ont été transférées sur la ligne 4 lors de son automatisation."
  },
  "MP 73": {
    nomComplet: "Matériel Pneu 1973",
    image: "mp73.png",
    constructeur: "Alstom, ANF, CEM",
    miseEnService: "1974",
    vitesseMax: "70 km/h",
    composition: "5 voitures",
    capacite: "~400 voyageurs",
    descriptionLongue: "Conçu pour la ligne 6, le MP 73 est reconnaissable à ses bogies spécifiques adaptés aux virages serrés et au long parcours sur viaduc. Il remplaçait les anciens MP 55."
  },
  "MF 77": {
    nomComplet: "Matériel Fer 1977",
    image: "mf77.png",
    constructeur: "Alsthom, ANF, Creusot-Loire",
    miseEnService: "1978",
    vitesseMax: "70 km/h",
    composition: "5 voitures",
    capacite: "~570 voyageurs",
    descriptionLongue: "Le MF 77 a été conçu pour les lignes longues et à grande affluence (7, 8, 13). Son design 'en double Gothique' était novateur et il est toujours en service après plusieurs rénovations."
  },
  "MF 88": {
    nomComplet: "Matériel Fer 1988",
    image: "mf88.png",
    constructeur: "Bombardier (ANF)",
    miseEnService: "1993",
    vitesseMax: "70 km/h",
    composition: "3 voitures",
    capacite: "~190 voyageurs",
    descriptionLongue: "Série expérimentale unique à la ligne 7bis, le MF 88 testait un système d'essieux orientables pour réduire le bruit et l'usure dans les courbes serrées. Il n'a pas été produit en grande série."
  },
  "MP 14 CC": {
    nomComplet: "Matériel Pneu 2014 (Conduite Conducteur)",
    image: "mp14cc.png",
    constructeur: "Alstom",
    miseEnService: "2023",
    vitesseMax: "80 km/h",
    composition: "5 voitures (boa)",
    capacite: "~580 voyageurs",
    descriptionLongue: "Version à conduite manuelle (CC) du MP 14, ce matériel à 5 voitures a été déployé sur la ligne 11 pour remplacer les vieux MP 59 et accompagner son prolongement."
  },
  "MP 14 CA": {
    nomComplet: "Matériel Pneu 2014 (Conduite Automatique)",
    image: "mp14ca.png",
    constructeur: "Alstom",
    miseEnService: "2019",
    vitesseMax: "80 km/h",
    composition: "6 ou 8 voitures (boa, auto)",
    capacite: "+1000 voyageurs (8v)",
    descriptionLongue: "Version automatique (CA) du MP 14. Elle existe en version 6 voitures (ligne 4) et 8 voitures (ligne 14), ce qui en fait les rames les plus longues du réseau parisien."
  },
  "MF 19 CC": {
    nomComplet: "Matériel Fer 2019 (Conduite Conducteur)",
    image: "mf19cc.png",
    constructeur: "Alstom, Bombardier",
    miseEnService: "2024 (en test)",
    vitesseMax: "85 km/h",
    composition: "5 voitures (boa)",
    capacite: "N/A (prototype)",
    descriptionLongue: "Le MF 19 est le futur matériel sur fer qui remplacera les MF 67, MF 77 et MF 88. Une rame est en test sur la ligne 10. Il existera en versions CC et CA."
  },
  "MR6V": {
    nomComplet: "Matériel Roulant 6 Voitures (GPE)",
    image: "mf19ca.png",
    constructeur: "Alstom",
    miseEnService: "Prévu pour 2026",
    vitesseMax: "110 km/h",
    composition: "6 voitures (boa, auto)",
    capacite: "~1000 voyageurs",
    descriptionLongue: "Matériel automatique à 6 voitures (MR6V) basé sur la plateforme Alstom Metropolis, conçu pour l'exploitation à haute capacité de la Ligne 15 du Grand Paris Express."
  },
  "MR3V": {
    nomComplet: "Matériel Roulant 3 Voitures (GPE)",
    image: "mf19ca.png",
    constructeur: "Alstom",
    miseEnService: "Prévu pour 2026",
    vitesseMax: "110 km/h",
    composition: "3 voitures (boa, auto)",
    capacite: "~500 voyageurs",
    descriptionLongue: "Version plus courte (MR3V) du nouveau matériel automatique du GPE, destinée aux lignes 16 et 17."
  },
  "MRV": {
    nomComplet: "Matériel Roulant Vitesse (GPE)",
    image: "mf19ca.png",
    constructeur: "Alstom",
    miseEnService: "Prévu pour 2027",
    vitesseMax: "120 km/h",
    composition: "3 voitures (auto)",
    capacite: "N/A",
    descriptionLongue: "Matériel automatique de type métro léger conçu pour la Ligne 18, capable d'atteindre des vitesses plus élevées sur de longues interstations."
  }
};


export const lignesMetro = [
  { 
    id: "1", nom: "Ligne 1", type: "actuel",
    terminus: ["La Défense", "Château de Vincennes"],
    ouverture: "1900", stations: 25, longueur: "16,6 km",
    materiel: [ 
      { nom: "MP 05", description: "Rames automatiques à 6 voitures." }
    ]
  },
  { 
    id: "2", nom: "Ligne 2", type: "actuel",
    terminus: ["Porte Dauphine", "Nation"],
    ouverture: "1900", stations: 25, longueur: "12,4 km",
    materiel: [
      { nom: "MF 01", description: "Rames boa climatisées à 5 voitures." }
    ]
  },
  { 
    id: "3", nom: "Ligne 3", type: "actuel",
    terminus: ["Pont de Levallois", "Gallieni"],
    ouverture: "1904", stations: 25, longueur: "11,7 km",
    materiel: [
      { nom: "MF 67", description: "Rames à 5 voitures, en cours de remplacement par des MF 19." }
    ]
  },
  { 
    id: "3bis", nom: "Ligne 3bis", type: "actuel",
    terminus: ["Gambetta", "Porte des Lilas"],
    ouverture: "1921 (1971 en 3bis)", stations: 4, longueur: "1,3 km",
    materiel: [
      { nom: "MF 67", description: "Rames courtes à 3 voitures, ex-Ligne 9." }
    ]
  },
  { 
    id: "4", nom: "Ligne 4", type: "actuel",
    terminus: ["Porte de Clignancourt", "Bagneux–Lucie Aubrac"],
    ouverture: "1908", stations: 29, longueur: "14 km",
    materiel: [
      { nom: "MP 14 CA", description: "Rames automatiques à 6 voitures." },
      { nom: "MP 05 IDFM", description: "Rames automatiques à 6 voitures (ex-Ligne 1)." },
      { nom: "MP 89 CA", description: "Rames automatiques à 6 voitures (ex-Ligne 14)." }
    ]
  },
  { 
    id: "5", nom: "Ligne 5", type: "actuel",
    terminus: ["Bobigny–Pablo Picasso", "Place d'Italie"],
    ouverture: "1906", stations: 22, longueur: "14,6 km",
    materiel: [
      { nom: "MF 01", description: "Rames boa climatisées à 5 voitures." }
    ]
  },
  { 
    id: "6", nom: "Ligne 6", type: "actuel",
    terminus: ["Charles de Gaulle–Étoile", "Nation"],
    ouverture: "1909", stations: 28, longueur: "13,7 km",
    materiel: [
      { nom: "MP 73", description: "Rames sur pneus à 5 voitures, rénovées." }
    ]
  },
  { 
    id: "7", nom: "Ligne 7", type: "actuel",
    terminus: ["La Courneuve–8 Mai 1945", "Mairie d'Ivry / Villejuif"],
    ouverture: "1910", stations: 38, longueur: "22,5 km",
    materiel: [
      { nom: "MF 77", description: "Rames à 5 voitures, en cours de rénovation." }
    ]
  },
  { 
    id: "7bis", nom: "Ligne 7bis", type: "actuel",
    terminus: ["Louis Blanc", "Pré-Saint-Gervais"],
    ouverture: "1911 (1967 en 7bis)", stations: 8, longueur: "3,1 km",
    materiel: [
      { nom: "MF 88", description: "Rames expérimentales à 3 voitures." }
    ]
  },
  { 
    id: "8", nom: "Ligne 8", type: "actuel",
    terminus: ["Balard", "Pointe du Lac"],
    ouverture: "1913", stations: 38, longueur: "23,4 km",
    materiel: [
      { nom: "MF 77", description: "Rames à 5 voitures." }
    ]
  },
  { 
    id: "9", nom: "Ligne 9", type: "actuel",
    terminus: ["Pont de Sèvres", "Mairie de Montreuil"],
    ouverture: "1922", stations: 37, longueur: "19,6 km",
    materiel: [
      { nom: "MF 01", description: "Rames boa climatisées à 5 voitures." }
    ]
  },
  { 
    id: "10", nom: "Ligne 10", type: "actuel",
    terminus: ["Boulogne–Pont de St-Cloud", "Gare d'Austerlitz"],
    ouverture: "1913", stations: 23, longueur: "11,7 km",
    materiel: [
      { nom: "MF 67", description: "Rames à 5 voitures." },
      { nom: "MF 19 CC", description: "Une rame prototype en test (Conduite Conducteur)." }
    ]
  },
  { 
    id: "11", nom: "Ligne 11", type: "actuel",
    terminus: ["Châtelet", "Rosny–Bois-Perrier"],
    ouverture: "1935", stations: 19, longueur: "11,7 km",
    materiel: [
      { nom: "MP 14 CC", description: "Rames neuves sur pneus à 5 voitures (Conduite Conducteur)." }
    ]
  },
  { 
    id: "12", nom: "Ligne 12", type: "actuel",
    terminus: ["Mairie d'Aubervilliers", "Mairie d'Issy"],
    ouverture: "1910", stations: 29, longueur: "17,2 km",
    materiel: [
      { nom: "MF 67", description: "Rames à 5 voitures." }
    ]
  },
  { 
    id: "13", nom: "Ligne 13", type: "actuel",
    terminus: ["Asnières–Gennevilliers / St-Denis", "Châtillon–Montrouge"],
    ouverture: "1911", stations: 32, longueur: "24,4 km",
    materiel: [
      { nom: "MF 77", description: "Rames à 5 voitures." }
    ]
  },
  { 
    id: "14", nom: "Ligne 14", type: "actuel",
    terminus: ["Mairie de St-Ouen", "Aéroport d'Orly"],
    ouverture: "1998", stations: 20, longueur: "27,8 km",
    materiel: [
      { nom: "MP 14 CA", description: "Rames automatiques à 8 voitures." }
    ]
  },
  { 
    id: "15", nom: "Ligne 15", type: "gpe",
    terminus: ["Pont de Sèvres", "Noisy–Champs"],
    ouverture: "Prévue 2026", stations: 16, longueur: "33 km",
    materiel: [
      { nom: "MR6V", description: "Futures rames automatiques à 6 voitures." }
    ]
  },
  { 
    id: "16", nom: "Ligne 16", type: "gpe",
    terminus: ["Saint-Denis Pleyel", "Noisy–Champs"],
    ouverture: "Prévue 2026", stations: 10, longueur: "29 km",
    materiel: [
      { nom: "MR3V", description: "Futures rames automatiques à 3 voitures." }
    ]
  },
  { 
    id: "17", nom: "Ligne 17", type: "gpe",
    terminus: ["Saint-Denis Pleyel", "Le Mesnil-Amelot"],
    ouverture: "Prévue 2026", stations: 9, longueur: "26,5 km",
    materiel: [
      { nom: "MR3V", description: "Futures rames automatiques à 3 voitures." }
    ]
  },
  { 
    id: "18", nom: "Ligne 18", type: "gpe",
    terminus: ["Aéroport d'Orly", "Versailles Chantiers"],
    ouverture: "Prévue 2027", stations: 10, longueur: "35 km",
    materiel: [
      { nom: "MRV", description: "Futures rames automatiques rapides." }
    ]
  }
];

// --- AJOUT DES COULEURS OFFICIELLES ---
export const ligneColors = {
  "1": "#FFCD00",
  "2": "#003CA6",
  "3": "#837902",
  "3bis": "#6EC4E8",
  "4": "#BE418D",
  "5": "#FF7E2E",
  "6": "#6ECA97",
  "7": "#FA9ABA",
  "7bis": "#6ECA97",
  "8": "#D27AD2",
  "9": "#B6BD00",
  "10": "#C9910D",
  "11": "#704B1C",
  "12": "#007852",
  "13": "#6EC4E8",
  "14": "#62259D",
  "15": "#DE005C",
  "16": "#F1B19B",
  "17": "#944D9B",
  "18": "#339999",
};

// --- AJOUT DES 303 STATIONS (Triées par ordre alphabétique) ---
export const stationsData = [
  { nom: "Abbesses", lignes: ["12"] },
  { nom: "Aéroport d'Orly", lignes: ["14", "18"] },
  { nom: "Aimé Césaire", lignes: ["12"] },
  { nom: "Alésia", lignes: ["4"] },
  { nom: "Alexandre Dumas", lignes: ["2"] },
  { nom: "Alma–Marceau", lignes: ["9"] },
  { nom: "Anatole France", lignes: ["3"] },
  { nom: "Anvers", lignes: ["2"] },
  { nom: "Argentine", lignes: ["1"] },
  { nom: "Arts et Métiers", lignes: ["3", "11"] },
  { nom: "Asnières–Gennevilliers–Les Courtilles", lignes: ["13"] },
  { nom: "Assemblée Nationale", lignes: ["12"] },
  { nom: "Aubervilliers–Pantin–Quatre Chemins", lignes: ["7"] },
  { nom: "Avron", lignes: ["2"] },
  { nom: "Bagneux–Lucie Aubrac", lignes: ["4"] },
  { nom: "Bagnolet (Gallieni)", lignes: ["3"] },
  { nom: "Balard", lignes: ["8"] },
  { nom: "Barbès–Rochechouart", lignes: ["2", "4"] },
  { nom: "Barbara", lignes: ["4"] },
  { nom: "Basilique de Saint-Denis", lignes: ["13"] },
  { nom: "Bastille", lignes: ["1", "5", "8"] },
  { nom: "Bel-Air", lignes: ["6"] },
  { nom: "Belleville", lignes: ["2", "11"] },
  { nom: "Bercy", lignes: ["6", "14"] },
  { nom: "Bérault", lignes: ["1"] },
  { nom: "Billancourt", lignes: ["9"] },
  { nom: "Bir-Hakeim", lignes: ["6"] },
  { nom: "Blanche", lignes: ["2"] },
  { nom: "Bobigny–Pablo Picasso", lignes: ["5"] },
  { nom: "Bobigny–La Folie", lignes: ["5"] },
  { nom: "Boissière", lignes: ["6"] },
  { nom: "Bolivar", lignes: ["7bis"] },
  { nom: "Bonne Nouvelle", lignes: ["8", "9"] },
  { nom: "Botzaris", lignes: ["7bis"] },
  { nom: "Boucicaut", lignes: ["8"] },
  { nom: "Boulogne–Jean Jaurès", lignes: ["10"] },
  { nom: "Boulogne–Pont de Saint-Cloud", lignes: ["10"] },
  { nom: "Bourse", lignes: ["3"] },
  { nom: "Bréguet–Sabin", lignes: ["5"] },
  { nom: "Brochant", lignes: ["13"] },
  { nom: "Buttes Chaumont", lignes: ["7bis"] },
  { nom: "Buzenval", lignes: ["9"] },
  { nom: "Cadet", lignes: ["7"] },
  { nom: "Cambronne", lignes: ["6"] },
  { nom: "Campo Formio", lignes: ["5"] },
  { nom: "Cardinal Lemoine", lignes: ["10"] },
  { nom: "Carrefour Pleyel", lignes: ["13"] },
  { nom: "Censier–Daubenton", lignes: ["7"] },
  { nom: "Champs-Élysées–Clemenceau", lignes: ["1", "13"] },
  { nom: "Chardon Lagache", lignes: ["10"] },
  { nom: "Charenton–Écoles", lignes: ["8"] },
  { nom: "Charles de Gaulle–Étoile", lignes: ["1", "2", "6"] },
  { nom: "Charles Michels", lignes: ["10"] },
  { nom: "Charonne", lignes: ["9"] },
  { nom: "Château de Vincennes", lignes: ["1"] },
  { nom: "Château d'Eau", lignes: ["4"] },
  { nom: "Château de Landon", lignes: ["7"] },
  { nom: "Château Rouge", lignes: ["4"] },
  { nom: "Châtelet", lignes: ["1", "4", "7", "11", "14"] },
  { nom: "Châtillon–Montrouge", lignes: ["13"] },
  { nom: "Chaussée d'Antin–La Fayette", lignes: ["7", "9"] },
  { nom: "Chemin Vert", lignes: ["8"] },
  { nom: "Chevaleret", lignes: ["6"] },
  { nom: "Cité", lignes: ["4"] },
  { nom: "Cluny–La Sorbonne", lignes: ["10"] },
  { nom: "Colonel Fabien", lignes: ["2"] },
  { nom: "Commerce", lignes: ["8"] },
  { nom: "Concorde", lignes: ["1", "8", "12"] },
  { nom: "Convention", lignes: ["12"] },
  { nom: "Corvisart", lignes: ["6"] },
  { nom: "Courcelles", lignes: ["2"] },
  { nom: "Couronnes", lignes: ["2"] },
  { nom: "Cour Saint-Émilion", lignes: ["14"] },
  { nom: "Créteil–L'Échat", lignes: ["8"] },
  { nom: "Créteil–Préfecture", lignes: ["8"] },
  { nom: "Créteil–Université", lignes: ["8"] },
  { nom: "Croix de Chavaux", lignes: ["9"] },
  { nom: "Crimée", lignes: ["7"] },
  { nom: "Danube", lignes: ["7bis"] },
  { nom: "Daumesnil", lignes: ["6", "8"] },
  { nom: "Denfert-Rochereau", lignes: ["4", "6"] },
  { nom: "Dupleix", lignes: ["6"] },
  { nom: "Dugommier", lignes: ["6"] },
  { nom: "Duroc", lignes: ["10", "13"] },
  { nom: "École Militaire", lignes: ["8"] },
  { nom: "École Vétérinaire de Maisons-Alfort", lignes: ["8"] },
  { nom: "Edgar Quinet", lignes: ["6"] },
  { nom: "Église d'Auteuil", lignes: ["10"] },
  { nom: "Église de Pantin", lignes: ["5"] },
  { nom: "Esplanade de La Défense", lignes: ["1"] },
  { nom: "Étienne Marcel", lignes: ["4"] },
  { nom: "Europe", lignes: ["3"] },
  { nom: "Exelmans", lignes: ["9"] },
  { nom: "Faidherbe–Chaligny", lignes: ["8"] },
  { nom: "Falguière", lignes: ["12"] },
  { nom: "Félix Faure", lignes: ["8"] },
  { nom: "Filles du Calvaire", lignes: ["8"] },
  { nom: "Fort d'Aubervilliers", lignes: ["7"] },
  { nom: "Franklin D. Roosevelt", lignes: ["1", "9"] },
  { nom: "Front Populaire", lignes: ["12"] },
  { nom: "Gabriel Péri", lignes: ["13"] },
  { nom: "Gaîté", lignes: ["13"] },
  { nom: "Gallieni (Bagnolet)", lignes: ["3"] },
  { nom: "Gambetta", lignes: ["3", "3bis"] },
  { nom: "Gare d'Austerlitz", lignes: ["5", "10"] },
  { nom: "Gare de l'Est", lignes: ["4", "5", "7"] },
  { nom: "Gare de Lyon", lignes: ["1", "14"] },
  { nom: "Gare du Nord", lignes: ["4", "5"] },
  { nom: "George V", lignes: ["1"] },
  { nom: "Glacière", lignes: ["6"] },
  { nom: "Goncourt", lignes: ["11"] },
  { nom: "Grands Boulevards", lignes: ["8", "9"] },
  { nom: "Guy Môquet", lignes: ["13"] },
  { nom: "Havre–Caumartin", lignes: ["3", "9"] },
  { nom: "Hoche", lignes: ["5"] },
  { nom: "Hôtel de Ville", lignes: ["1", "11"] },
  { nom: "Invalides", lignes: ["8", "13"] },
  { nom: "Jacques Bonsergent", lignes: ["5"] },
  { nom: "Jasmin", lignes: ["9"] },
  { nom: "Jaurès", lignes: ["2", "5", "7bis"] },
  { nom: "Javel–André Citroën", lignes: ["10"] },
  { nom: "Jourdain", lignes: ["11"] },
  { nom: "Jules Joffrin", lignes: ["12"] },
  { nom: "Jussieu", lignes: ["7", "10"] },
  { nom: "Kléber", lignes: ["6"] },
  { nom: "La Courneuve–8 Mai 1945", lignes: ["7"] },
  { nom: "La Défense", lignes: ["1"] },
  { nom: "Lamarck–Caulaincourt", lignes: ["12"] },
  { nom: "La Motte-Picquet–Grenelle", lignes: ["6", "8", "10"] },
  { nom: "La Muette", lignes: ["9"] },
  { nom: "La Tour-Maubourg", lignes: ["8"] },
  { nom: "Laumière", lignes: ["5"] },
  { nom: "Le Kremlin-Bicêtre", lignes: ["7"] },
  { nom: "Les Agnettes", lignes: ["13"] },
  { nom: "Les Gobelins", lignes: ["7"] },
  { nom: "Les Halles", lignes: ["4"] },
  { nom: "Les Sablons", lignes: ["1"] },
  { nom: "Liberté", lignes: ["8"] },
  { nom: "Liège", lignes: ["13"] },
  { nom: "Lilas (Mairie des Lilas)", lignes: ["11"] },
  { nom: "Louis Aragon (Villejuif)", lignes: ["7"] },
  { nom: "Louis Blanc", lignes: ["7", "7bis"] },
  { nom: "Louise Michel", lignes: ["3"] },
  { nom: "Lourmel", lignes: ["8"] },
  { nom: "Louvre–Rivoli", lignes: ["1"] },
  { nom: "Mabillon", lignes: ["10"] },
  { nom: "Madeleine", lignes: ["8", "12", "14"] },
  { nom: "Mairie d'Aubervilliers", lignes: ["12"] },
  { nom: "Mairie de Clichy", lignes: ["13"] },
  { nom: "Mairie d'Issy", lignes: ["12"] },
  { nom: "Mairie d'Ivry", lignes: ["7"] },
  { nom: "Mairie des Lilas", lignes: ["11"] },
  { nom: "Mairie de Montreuil", lignes: ["9"] },
  { nom: "Mairie de Montrouge", lignes: ["4"] },
  { nom: "Mairie de Saint-Ouen", lignes: ["13", "14"] },
  { nom: "Maison Blanche", lignes: ["7"] },
  { nom: "Maisons-Alfort–Les Juilliottes", lignes: ["8"] },
  { nom: "Maisons-Alfort–Stade", lignes: ["8"] },
  { nom: "Malakoff–Plateau de Vanves", lignes: ["13"] },
  { nom: "Malakoff–Rue Étienne Dolet", lignes: ["13"] },
  { nom: "Malesherbes", lignes: ["3"] },
  { nom: "Maraîchers", lignes: ["9"] },
  { nom: "Marcadet–Poissonniers", lignes: ["4", "12"] },
  { nom: "Marcel Sembat", lignes: ["9"] },
  { nom: "Marx Dormoy", lignes: ["12"] },
  { nom: "Maubert–Mutualité", lignes: ["10"] },
  { nom: "Ménilmontant", lignes: ["2"] },
  { nom: "Michel-Ange–Auteuil", lignes: ["9", "10"] },
  { nom: "Michel-Ange–Molitor", lignes: ["9", "10"] },
  { nom: "Michel Bizot", lignes: ["8"] },
  { nom: "Mirabeau", lignes: ["10"] },
  { nom: "Miromesnil", lignes: ["9", "13"] },
  { nom: "Monceau", lignes: ["2"] },
  { nom: "Montgallet", lignes: ["8"] },
  { nom: "Montparnasse–Bienvenüe", lignes: ["4", "6", "12", "13"] },
  { nom: "Mouton-Duvernet", lignes: ["4"] },
  { nom: "Nation", lignes: ["1", "2", "6", "9"] },
  { nom: "Nationale", lignes: ["6"] },
  { nom: "Notre-Dame-de-Lorette", lignes: ["12"] },
  { nom: "Notre-Dame-des-Champs", lignes: ["12"] },
  { nom: "Oberkampf", lignes: ["5", "9"] },
  { nom: "Odéon", lignes: ["4", "10"] },
  { nom: "Olympiades", lignes: ["14"] },
  { nom: "Opéra", lignes: ["3", "7", "8"] },
  { nom: "Ourcq", lignes: ["5"] },
  { nom: "Palais Royal–Musée du Louvre", lignes: ["1", "7"] },
  { nom: "Parmentier", lignes: ["3"] },
  { nom: "Passy", lignes: ["6"] },
  { nom: "Pasteur", lignes: ["6", "12"] },
  { nom: "Pelleport", lignes: ["3bis"] },
  { nom: "Père Lachaise", lignes: ["2", "3"] },
  { nom: "Pernety", lignes: ["13"] },
  { nom: "Philippe Auguste", lignes: ["2"] },
  { nom: "Picpus", lignes: ["6"] },
  { nom: "Pierre et Marie Curie", lignes: ["7"] },
  { nom: "Pigalle", lignes: ["2", "12"] },
  { nom: "Place d'Italie", lignes: ["5", "6", "7"] },
  { nom: "Place de Clichy", lignes: ["2", "13"] },
  { nom: "Place des Fêtes", lignes: ["7bis", "11"] },
  { nom: "Place Monge", lignes: ["7"] },
  { nom: "Plaisance", lignes: ["13"] },
  { nom: "Pointe du Lac", lignes: ["8"] },
  { nom: "Poissonnière", lignes: ["7"] },
  { nom: "Pont de Levallois–Bécon", lignes: ["3"] },
  { nom: "Pont de Neuilly", lignes: ["1"] },
  { nom: "Pont de Sèvres", lignes: ["9"] },
  { nom: "Pont Marie", lignes: ["7"] },
  { nom: "Pont Neuf", lignes: ["7"] },
  { nom: "Porte d'Auteuil", lignes: ["10"] },
  { nom: "Porte d'Aubervilliers", lignes: ["12"] },
  { nom: "Porte de Bagnolet", lignes: ["3"] },
  { nom: "Porte de Champerret", lignes: ["3"] },
  { nom: "Porte de Charenton", lignes: ["8"] },
  { nom: "Porte de Choisy", lignes: ["7"] },
  { nom: "Porte de Clichy", lignes: ["13", "14"] },
  { nom: "Porte de Clignancourt", lignes: ["4"] },
  { nom: "Porte Dauphine", lignes: ["2"] },
  { nom: "Porte de Gentilly", lignes: ["14"] },
  { nom: "Porte d'Ivry", lignes: ["7"] },
  { nom: "Porte de la Chapelle", lignes: ["12"] },
  { nom: "Porte de la Villette", lignes: ["7"] },
  { nom: "Porte de Montreuil", lignes: ["9"] },
  { nom: "Porte de Pantin", lignes: ["5"] },
  { nom: "Porte de Saint-Cloud", lignes: ["9"] },
  { nom: "Porte de Saint-Ouen", lignes: ["13"] },
  { nom: "Porte de Vanves", lignes: ["13"] },
  { nom: "Porte de Versailles", lignes: ["12"] },
  { nom: "Porte de Vincennes", lignes: ["1"] },
  { nom: "Porte des Lilas", lignes: ["3bis", "11"] },
  { nom: "Porte Dorée", lignes: ["8"] },
  { nom: "Porte d'Orléans", lignes: ["4"] },
  { nom: "Pré-Saint-Gervais", lignes: ["7bis"] },
  { nom: "Pyramides", lignes: ["7", "14"] },
  { nom: "Quai de la Gare", lignes: ["6"] },
  { nom: "Quai de la Rapée", lignes: ["5"] },
  { nom: "Quatre-Septembre", lignes: ["3"] },
  { nom: "Rambuteau", lignes: ["11"] },
  { nom: "Ranelagh", lignes: ["9"] },
  { nom: "Raspail", lignes: ["4", "6"] },
  { nom: "Réaumur–Sébastopol", lignes: ["3", "4"] },
  { nom: "Reuilly–Diderot", lignes: ["1", "8"] },
  { nom: "République", lignes: ["3", "5", "8", "9", "11"] },
  { nom: "Richard-Lenoir", lignes: ["5"] },
  { nom: "Richelieu–Drouot", lignes: ["8", "9"] },
  { nom: "Riquet", lignes: ["7"] },
  { nom: "Robespierre", lignes: ["9"] },
  { nom: "Rome", lignes: ["2"] },
  { nom: "Rosny–Bois-Perrier", lignes: ["11"] },
  { nom: "Rue de la Pompe", lignes: ["9"] },
  { nom: "Rue des Boulets", lignes: ["9"] },
  { nom: "Rue du Bac", lignes: ["12"] },
  { nom: "Rue Saint-Maur", lignes: ["3"] },
  { nom: "Saint-Ambroise", lignes: ["9"] },
  { nom: "Saint-Augustin", lignes: ["9"] },
  { nom: "Saint-Denis–Porte de Paris", lignes: ["13"] },
  { nom: "Saint-Denis–Université", lignes: ["13"] },
  { nom: "Saint-Fargeau", lignes: ["3bis"] },
  { nom: "Saint-François-Xavier", lignes: ["13"] },
  { nom: "Saint-Georges", lignes: ["12"] },
  { nom: "Saint-Germain-des-Prés", lignes: ["4"] },
  { nom: "Saint-Jacques", lignes: ["6"] },
  { nom: "Saint-Lazare", lignes: ["3", "12", "13", "14"] },
  { nom: "Saint-Mandé", lignes: ["1"] },
  { nom: "Saint-Marcel", lignes: ["5"] },
  { nom: "Saint-Michel", lignes: ["4"] },
  { nom: "Saint-Ouen", lignes: ["14"] },
  { nom: "Saint-Paul", lignes: ["1"] },
  { nom: "Saint-Philippe du Roule", lignes: ["9"] },
  { nom: "Saint-Placide", lignes: ["4"] },
  { nom: "Saint-Sébastien–Froissart", lignes: ["8"] },
  { nom: "Saint-Sulpice", lignes: ["4"] },
  { nom: "Ségur", lignes: ["10"] },
  { nom: "Sentier", lignes: ["3"] },
  { nom: "Serge Gainsbourg", lignes: ["11"] },
  { nom: "Sèvres–Babylone", lignes: ["10", "12"] },
  { nom: "Sèvres–Lecourbe", lignes: ["6"] },
  { nom: "Simplon", lignes: ["4"] },
  { nom: "Solférino", lignes: ["12"] },
  { nom: "Stalingrad", lignes: ["2", "5", "7"] },
  { nom: "Strasbourg–Saint-Denis", lignes: ["4", "8", "9"] },
  { nom: "Sully–Morland", lignes: ["7"] },
  { nom: "Télégraphe", lignes: ["11"] },
  { nom: "Temple", lignes: ["3"] },
  { nom: "Ternes", lignes: ["2"] },
  { nom: "Tolbiac", lignes: ["7"] },
  { nom: "Trinité–d'Estienne d'Orves", lignes: ["12"] },
  { nom: "Trocadéro", lignes: ["6", "9"] },
  { nom: "Tuileries", lignes: ["1"] },
  { nom: "Ulm (Place du Panthéon)", lignes: ["10"] },
  { nom: "Vaneau", lignes: ["10"] },
  { nom: "Varenne", lignes: ["13"] },
  { nom: "Vaugirard", lignes: ["12"] },
  { nom: "Vavin", lignes: ["4"] },
  { nom: "Verdun-Sud", lignes: ["4"] },
  { nom: "Victor Hugo", lignes: ["2"] },
  { nom: "Villejuif–L'Haÿ-les-Roses", lignes: ["14"] },
  { nom: "Villejuif–Louis Aragon", lignes: ["7"] },
  { nom: "Villejuif–Paul Vaillant-Couturier", lignes: ["7"] },
  { nom: "Villiers", lignes: ["2", "3"] },
  { nom: "Volontaires", lignes: ["12"] },
  { nom: "Voltaire", lignes: ["9"] },
  { nom: "Wagram", lignes: ["3"] },
];